# Generated by Django 3.2.5 on 2021-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='hello@hello.com', max_length=100)),
                ('name', models.CharField(default='name', max_length=100)),
                ('desc', models.CharField(default='desc', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
